import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'nav.dashboard': 'Dashboard',
    'nav.eventos': 'Eventos',
    'nav.pacientes': 'Pacientes',
    'nav.citas': 'Citas',
    'nav.cirugias': 'Cirugías',
    'nav.triage': 'Triages Pendientes',
    'nav.consultas': 'Consultas',
    'nav.seguimientos': 'Seguimientos',
    'nav.usuarios': 'Usuarios',
    'nav.variables': 'Variables',
    'nav.auditoria': 'Auditoría',
    'nav.logout': 'Cerrar Sesión',
    'panel.recepcion': 'Panel de Recepción',
    'panel.triage': 'Panel de Triage',
    'panel.medico': 'Panel Médico',
    'panel.admin': 'Panel de Administración',
    'notif.recent': 'Actividad Reciente',
    'notif.view_all': 'Ver todo',
    'notif.no_activity': 'Sin actividad reciente',
    'notif.last_actions': 'Últimas acciones en el sistema',
    'lang.toggle': 'Cambiar a Inglés',
    'common.loading': 'Cargando…',
    'medico.title': 'Consultorio Médico',
    'medico.subtitle': 'Pacientes en espera y consultas completadas',
    'medico.stats.waiting': 'En Espera',
    'medico.stats.completed': 'Completadas Hoy',
    'medico.stats.total': 'Total Consultas',
    'medico.stats.surgeries': 'Cirugías Iniciadas',
    'medico.patients.waiting': 'Pacientes en Espera',
    'medico.action.start_consultation': 'Iniciar Consulta',
    'medico.form.title': 'Consulta Médica',
    'medico.form.patient_data': 'Datos del Paciente',
    'medico.form.phone': 'Teléfono',
    'medico.form.age': 'Edad',
    'medico.form.sex': 'Sexo',
    'medico.form.years': 'años',
    'medico.form.vitals': 'Signos Vitales',
    'medico.form.vitals.temp': 'Temperatura',
    'medico.form.vitals.bp': 'Presión',
    'medico.form.vitals.hr': 'Ritmo',
    'medico.form.vitals.rr': 'Frecuencia Respiratoria',
    'medico.form.vitals.o2': 'Saturación O2',
    'medico.form.vitals.glucose': 'Glucosa',
    'medico.form.vitals.weight': 'Peso',
    'medico.form.vitals.height': 'Altura',
    'medico.form.medical_info': 'Información Médica',
    'medico.form.allergies': 'Alergias',
    'medico.form.background': 'Antecedentes',
    'medico.form.reason_current': 'Motivo de Consulta y Padecimiento Actual',
    'medico.form.reason': 'Motivo de Consulta *',
    'medico.form.current_illness': 'Padecimiento Actual *',
    'medico.form.physical_exam_title': 'Exploración Física',
    'medico.form.physical_exam': 'Hallazgos de Exploración Física *',
    'medico.form.diagnosis_title': 'Diagnóstico',
    'medico.form.diagnosis': 'Diagnóstico Médico *',
    'medico.form.treatment_plan': 'Plan de Tratamiento',
    'medico.form.treatment': 'Tratamiento *',
    'medico.form.medications': 'Medicamentos Recetados',
    'medico.form.add_medication': 'Agregar Medicamento',
    'medico.form.medication_name': 'Medicamento',
    'medico.form.medication_dose': 'Dosis',
    'medico.form.medication_freq': 'Frecuencia',
    'medico.form.medication_duration': 'Duración',
    'medico.form.studies': 'Estudios o Análisis Indicados',
    'medico.form.add_study': 'Agregar Estudio',
    'medico.form.study_type': 'Tipo de Estudio',
    'medico.form.study_indications': 'Indicaciones',
    'medico.form.recommendations': 'Recomendaciones',
    'medico.form.next_consultation': 'Próxima Consulta',
    'medico.form.requires_followup': 'Aplica seguimiento para evento futuro',
    'medico.form.followup_note': 'Nota para seguimiento',
    'medico.form.followup_note_placeholder': 'Ej: Agendar control, revisar resultados, dar seguimiento a tratamiento…',
    'medico.form.followup_event': 'Evento para agendar',
    'medico.form.followup_event_pending': 'Pendiente (sin evento)',
    'medico.form.followup_calendar': 'Disponibilidad en calendario',
    'medico.form.followup_calendar_empty': 'Este evento no tiene horarios para la especialidad de la cita.',
    'medico.form.requires_surgery': 'Requiere Proceso de Cirugía',
    'medico.form.cancel': 'Cancelar',
    'medico.form.complete': 'Completar Consulta',
    'medico.form.back': 'Volver',
    'medico.form.no_type': 'Sin tipo de cita',
    'medico.form.patient': 'Paciente',
    'dash.admin.title': '¡Buenos días, Administrador!',
    'dash.admin.subtitle': 'Panel de administración y gestión del sistema',
    'dash.admin.badge': 'Control total del sistema médico',
    'dash.admin.active_users': 'Usuarios Activos',
    'dash.admin.total_patients': 'Total Pacientes',
    'dash.admin.audit_logs': 'Registros Auditoría',
    'dash.admin.roles_config': 'Roles Configurados',
    'dash.admin.sys_users': 'Usuarios del Sistema',
    'dash.admin.users': 'usuarios',
    'dash.admin.reception': 'Recepción',
    'dash.admin.triage': 'Triage',
    'dash.admin.doctor': 'Médico',
    'dash.admin.admin': 'Administrador',
    'dash.admin.manage_users': 'Gestionar Usuarios',
    'dash.admin.quick_actions': 'Acciones Rápidas',
    'dash.admin.create_user': 'Crear Usuario',
    'dash.admin.variables': 'Variables',
    'dash.admin.view_audit': 'Ver Auditoría',
    'dash.admin.manage_patients': 'Gestionar Pacientes',
    'dash.admin.sys_status': 'Estado del Sistema',
    'dash.admin.os': 'Sistema Operativo',
    'dash.admin.normal': 'Normal',
    'dash.admin.db': 'Base de Datos',
    'dash.admin.active': 'Activa',
    'dash.admin.connectivity': 'Conectividad',
    'dash.admin.optimal': 'Óptima',
    'dash.admin.recent_activity': 'Actividad Reciente',
    'dash.admin.view_all': 'Ver Todo',
    'dash.admin.no_activity': 'No hay actividad reciente registrada en la base de datos.',
    'dash.recep.title': '¡Buenos días, Recepción!',
    'dash.recep.subtitle': 'Bienvenido al sistema de gestión médica',
    'dash.recep.no_event': 'Sin evento activo',
    'dash.recep.total_appts_today': 'Total de Citas Hoy',
    'dash.recep.registered_patients': 'Pacientes Registrados',
    'dash.recep.completed_appts': 'Citas Completadas',
    'dash.recep.active_events': 'Eventos Activos',
    'dash.recep.appts_today': 'Citas de Hoy',
    'dash.recep.appts': 'citas',
    'dash.recep.scheduled': 'Programada',
    'dash.recep.in_triage': 'En Triage',
    'dash.recep.in_consultation': 'En Consulta',
    'dash.recep.completed': 'Completada',
    'dash.recep.view_all_appts': 'Ver todas las citas',
    'dash.recep.quick_actions': 'Acciones Rápidas',
    'dash.recep.register_patient': 'Registrar Paciente',
    'dash.recep.schedule_appt': 'Agendar Cita',
    'dash.recep.view_events': 'Ver Eventos',
    'dash.recep.view_surgeries': 'Ver Cirugías',
    'dash.triage.title': '¡Buenos días, Enfermería!',
    'dash.triage.subtitle': 'Gestión de signos vitales y triage de pacientes',
    'dash.triage.patients_today': 'pacientes en lista de hoy',
    'dash.triage.pending_triage': 'Pendientes de Triage',
    'dash.triage.in_progress': 'En Proceso',
    'dash.triage.completed': 'Completados',
    'dash.triage.patients_today_title': 'Pacientes de Hoy',
    'dash.triage.patients': 'pacientes',
    'dash.triage.go_to_triage': 'Ir a módulo de Triage',
    'dash.triage.activity_today': 'Actividad de Hoy',
    'dash.triage.total_patients': 'Total de Pacientes',
    'dash.triage.triage_progress': 'Progreso de Triage',
    'dash.triage.avg_time': 'Tiempo Promedio',
    'dash.triage.min': 'min',
    'dash.triage.per_patient': 'por paciente',
    'dash.triage.pending': 'Pendiente',
    'dash.medico.title': '¡Buenos días, Doctor!',
    'dash.medico.subtitle': 'Panel de consultas y seguimiento médico',
    'dash.medico.badge': 'Sistema de gestión médica integral',
    'dash.medico.appts_today': 'Consultas Hoy',
    'dash.medico.followups': 'Seguimientos',
    'dash.medico.pending': 'pendientes',
    'dash.medico.active_surgeries': 'Cirugías Activas',
    'dash.medico.my_patients': 'Mis Pacientes',
    'dash.medico.patients_today': 'Pacientes de Hoy',
    'dash.medico.consultations': 'consultas',
    'dash.medico.go_to_consultations': 'Ir a Consultas',
    'dash.medico.followups_title': 'Seguimientos',
    'dash.medico.pending_schedule': 'Pendientes de Agendar',
    'dash.medico.scheduled_appts': 'Citas Agendadas',
    'dash.medico.total': 'Total',
    'dash.medico.view_all': 'Ver Todos',
    'dash.medico.quick_actions': 'Acciones Rápidas',
    'dash.medico.consult_patient': 'Consultar Paciente',
    'dash.medico.view_patients': 'Ver Pacientes',
    'dash.medico.manage_surgeries': 'Gestionar Cirugías',
    'consultas.title': 'Consultas Médicas',
    'consultas.subtitle': 'Pacientes listos para consulta',
    'consultas.years': 'años',
    'consultas.no_observations': 'Sin observaciones',
    'consultas.in_consultation': 'En Consulta',
    'consultas.empty_title': 'No hay pacientes en consulta',
    'consultas.empty_desc': 'Los pacientes aparecerán aquí después de pasar por triage',
    'cirugias.title': 'Gestión de Cirugías',
    'cirugias.subtitle': 'Procesos quirúrgicos, estudios socioeconómicos y seguimientos',
    'cirugias.start_process': 'Iniciar Proceso de Cirugía',
    'cirugias.total': 'Total',
    'cirugias.pending': 'Pendientes',
    'cirugias.scheduled': 'Programadas',
    'cirugias.completed': 'Realizadas',
    'cirugias.followups': 'Seguimientos',
    'cirugias.search_placeholder': 'Buscar por paciente, diagnóstico o médico...',
    'cirugias.all_statuses': 'Todos los estados',
    'cirugias.status.pending_study': 'Pendiente de Estudio',
    'cirugias.status.study_completed': 'Estudio Completado',
    'cirugias.status.scheduled': 'Programada',
    'cirugias.status.completed': 'Realizada',
    'cirugias.status.cancelled': 'Cancelada',
    'cirugias.specialty': 'Especialidad',
    'cirugias.unspecified': 'No especificada',
    'cirugias.location': 'Lugar',
    'cirugias.unassigned': 'No asignado',
    'cirugias.est_cost': 'Costo Estimado',
    'cirugias.view_details': 'Ver Detalles',
    'cirugias.do_study': 'Realizar Estudio',
    'cirugias.add_followup': 'Agregar Seguimiento',
    'cirugias.empty_title': 'No hay cirugías registradas',
    'cirugias.empty_desc': 'Comienza iniciando el primer proceso de cirugía',
    'seg.title': 'Seguimientos Médicos',
    'seg.subtitle': 'Gestión y control de seguimientos de pacientes',
    'seg.new': 'Nuevo Seguimiento',
    'seg.pending': 'Pendientes',
    'seg.scheduled': 'Agendados',
    'seg.completed': 'Completados',
    'seg.search': 'Buscar por nombre, expediente o diagnóstico...',
    'seg.all': 'Todos',
    'seg.status.pending': 'Pendiente de Agendar',
    'seg.status.scheduled': 'Cita Agendada',
    'seg.status.completed': 'Completado',
    'seg.diagnosis': 'Diagnóstico',
    'seg.glucose': 'Glucosa en sangre',
    'seg.required_exams': 'Exámenes requeridos',
    'seg.next_appt': 'Próxima cita',
    'seg.pharmacy': 'Remisión a Farmacia',
    'seg.view_details': 'Ver Detalles',
    'seg.edit': 'Editar',
    'seg.quick_followup': 'Seguimiento rápido...',
    'seg.requires_scheduling': 'Agendar en evento futuro',
    'seg.followup_note': 'Nota de seguimiento',
    'seg.followup_note_placeholder': 'Ej: Paciente requiere control, revisar resultados, continuar tratamiento…',
    'seg.followup_event': 'Evento a agendar',
    'seg.followup_event_pending': 'Pendiente (sin evento)',
    'seg.in_15_days': 'En 15 días',
    'seg.in_1_month': 'En 1 mes',
    'seg.in_3_months': 'En 3 meses',
    'seg.in_6_months': 'En 6 meses',
    'seg.manual_schedule': 'Agendar manual',
    'seg.empty_title': 'No hay seguimientos',
    'seg.empty_desc_filtered': 'No se encontraron seguimientos con los filtros aplicados',
    'seg.empty_desc': 'Los seguimientos de pacientes aparecerán aquí',
    'seg.clear_filters': 'Limpiar filtros',
    'triage.title': 'Estación de Triage',
    'triage.subtitle': 'Pacientes con cita para hoy -',
    'triage.no_event': 'Sin evento activo',
    'triage.total_today': 'Total Pacientes Hoy',
    'triage.no_capture': 'Sin Captura',
    'triage.in_progress': 'En Proceso',
    'triage.completed': 'Completados',
    'triage.search': 'Buscar paciente en la lista de hoy...',
    'triage.available_patients': 'Pacientes Disponibles',
    'triage.no_appt_type': 'Sin tipo de cita',
    'triage.scheduled_for': 'Agendado para el',
    'triage.assigned_time': 'Hora asignada:',
    'triage.temp': 'Temperatura',
    'triage.pressure': 'Presión',
    'triage.empty_patients': 'No hay pacientes disponibles',
    'triage.modal_title': 'Signos Vitales - Triage',
    'triage.appt': 'Cita:',
    'triage.vitals': 'Signos Vitales',
    'triage.temp_input': 'Temperatura (°C) *',
    'triage.normal': 'Normal:',
    'triage.pressure_input': 'Presión Arterial *',
    'triage.hr_input': 'Ritmo Cardíaco (bpm) *',
    'triage.resp_input': 'Frecuencia Respiratoria (rpm) *',
    'triage.o2_input': 'Saturación de Oxígeno (%)',
    'triage.glucose_input': 'Glucosa (mg/dL)',
    'triage.anthropometry': 'Antropometría',
    'triage.weight_input': 'Peso (kg) *',
    'triage.height_input': 'Altura (cm) *',
    'triage.imc_calc': 'IMC Calculado',
    'triage.underweight': 'Bajo peso',
    'triage.normal_weight': 'Normal',
    'triage.overweight': 'Sobrepeso',
    'triage.obesity': 'Obesidad',
    'triage.observations': 'Observaciones',
    'triage.obs_placeholder': 'Observaciones adicionales sobre el estado del paciente...',
    'triage.out_of_range': 'Signos Vitales Fuera de Rango',
    'triage.cancel': 'Cancelar',
    'triage.save_progress': 'Guardar en Proceso',
    'triage.complete_send': 'Completar y Enviar a Consulta',
    'triage.close': 'Cerrar',

    // Pacientes
    'pac.title_medico': 'Mis Pacientes',
    'pac.title_recepcion': 'Gestión de Pacientes',
    'pac.subtitle_medico': 'Pacientes que han asistido o están agendados en el sistema',
    'pac.subtitle_recepcion': 'Registra y administra los expedientes de pacientes',
    'pac.new': 'Nuevo Paciente',
    'pac.search': 'Buscar por nombre, expediente o teléfono...',
    'pac.all': 'todos',
    'pac.scheduled': 'agendados',
    'pac.attended': 'atendidos',
    'pac.citas': 'citas',
    'pac.not_found': 'No se encontraron pacientes',
    'pac.try_another': 'Intenta con otro término de búsqueda',
    'pac.start_registering': 'Comienza registrando tu primer paciente',
    'pac.register_first': 'Registrar Primer Paciente',
    'pac.register_new': 'Registrar Nuevo Paciente',
    'pac.full_name': 'Nombre Completo',
    'pac.dob': 'Fecha de Nacimiento',
    'pac.sex': 'Sexo',
    'pac.phone': 'Teléfono',
    'pac.city': 'Ciudad',
    'pac.nationality': 'Nacionalidad',
    'pac.mexican': 'Mexicana',
    'pac.american': 'Americana',
    'pac.passport': 'Pasaporte Americano',
    'pac.curp': 'CURP',
    'pac.photo': 'Fotografía del Paciente (Opcional)',
    'pac.select_image': 'Seleccionar Imagen',
    'pac.no_file': 'Ningún archivo seleccionado',
    'pac.note': 'Nota:',
    'pac.auto_id': 'Se generará automáticamente un número de expediente único para este paciente.',
    'pac.cancel': 'Cancelar',
    'pac.saving': 'Guardando...',
    'pac.register': 'Registrar Paciente',
    'pac.age': 'Edad',
    'pac.years': 'años',
    'pac.birth': 'Nacimiento',
    'pac.registration': 'Registro',
    'pac.full_record': 'Ver Expediente Completo',
    'pac.start_surgery': 'Iniciar Proceso de Cirugía',

    // Citas
    'citas.not_active': 'Este evento no está activo. No se pueden agendar citas.',
    'citas.day_of_only': 'Para el día de la cita solo se permite cancelar o registrar llegada.',
    'citas.slot_taken': 'Ese horario ya fue ocupado por otra cita.',
    'citas.title': 'Citas',
    'citas.subtitle': 'Administrador general de citas: muestra todas las citas (todos los eventos y especialidades) y permite agendar en espacios disponibles.',
    'citas.no_events': 'No hay eventos disponibles',
    'citas.create_event': 'Crea un evento con fechas y horarios para habilitar espacios disponibles.',
    'citas.agenda': 'Agenda',
    'citas.followups_pending': 'Seguimientos pendientes',
    'citas.followups_selected': 'Seguimiento seleccionado',
    'citas.followups_clear': 'Quitar',
    'citas.followups_pick_slot': 'Selecciona un bloque en el calendario para agendar.',
    'citas.followups_empty': 'No hay seguimientos pendientes de agendar.',
    'citas.followups_action': 'Agendar',
    'citas.followups_msg_selected': 'Seguimiento listo. Selecciona un bloque en el calendario para agendar.',
    'citas.followups_wrong_event': 'Este seguimiento solo se puede agendar en el evento seleccionado. Elige un bloque dentro de ese evento.',

    // Eventos
    'eventos.no_date': 'Sin fecha',
    'eventos.title': 'Agenda de eventos',
    'eventos.subtitle': 'Visualiza los eventos como tarjetas y entra a su detalle para consultar información, especialidades y agenda.',
    'eventos.new': 'Nuevo evento',
    'eventos.no_city_msg': 'Tu usuario no tiene ciudad asignada. Asigna una ciudad (o ciudades) al usuario para poder ver eventos.',
    'eventos.no_events_admin': 'No hay eventos registrados',
    'eventos.no_events_city': 'No hay eventos para tu ciudad',
    'eventos.create_to_enable': 'Crea un evento para habilitar horarios y cupos.',
    'eventos.assigned_city': 'Ciudad asignada:',
    'eventos.create': 'Crear evento',
    'eventos.readonly': 'Solo lectura',
    'eventos.inscriptions': 'Inscripciones',
    'eventos.event': 'Evento',
    'eventos.no_specialties': 'Sin especialidades registradas',
    'eventos.specialties': 'especialidades',
    'eventos.schedules': 'horarios',
    'eventos.view': 'Ver evento',
    'eventos.edit': 'Editar',
    'eventos.delete': 'Eliminar',
    'eventos.delete_title': 'Eliminar evento',
    'eventos.delete_desc': 'Se eliminará el evento "{0}" y también especialidades, horarios, practicantes, citas, triage y notas médicas relacionadas.',
    'eventos.cancel': 'Cancelar',
    'eventos.delete_test': 'Eliminar (pruebas)',
    'eventos.delete_test_title': 'Eliminar evento (modo pruebas)',
    'eventos.delete_test_desc': 'El evento ya finalizó y normalmente es de solo lectura. En modo pruebas se permite eliminarlo de forma forzada.',

    // Usuarios
    'usuarios.title': 'Gestión de Usuarios',
    'usuarios.subtitle': 'Administra los usuarios del sistema',
    'usuarios.create': 'Crear Usuario',
    'usuarios.filters': 'Filtros',
    'usuarios.search_label': 'Buscar',
    'usuarios.search_placeholder': 'Nombre, email, rol, ciudad o especialidad...',
    'usuarios.role_label': 'Rol',
    'usuarios.role_all': 'Todos',
    'usuarios.role_admin': 'Administrador',
    'usuarios.role_reception': 'Recepción',
    'usuarios.role_triage': 'Triage',
    'usuarios.role_doctor': 'Médico',
    'usuarios.city_label': 'Ciudad',
    'usuarios.city_all': 'Todas',
    'usuarios.status_label': 'Estado',
    'usuarios.status_all': 'Todos',
    'usuarios.status_active': 'Activos',
    'usuarios.status_inactive': 'Inactivos (todos)',
    'usuarios.status_inactive_manual': 'Inactivo manual',
    'usuarios.status_out_of_date': 'Fuera de vigencia',
    'usuarios.order_label': 'Orden',
    'usuarios.order_name_asc': 'Nombre (A-Z)',
    'usuarios.order_name_desc': 'Nombre (Z-A)',
    'usuarios.order_role': 'Rol',
    'usuarios.order_city': 'Ciudad',
    'usuarios.clear': 'Limpiar',
    'usuarios.users_title': 'Usuarios',
    'usuarios.showing': 'Mostrando:',
    'usuarios.active': 'Activos:',
    'usuarios.inactive': 'Inactivos:',
    'usuarios.col_user': 'Usuario',
    'usuarios.col_email': 'Email',
    'usuarios.col_role': 'Rol',
    'usuarios.col_city': 'Ciudad',
    'usuarios.col_cities': 'Ciudades',
    'usuarios.col_specialty': 'Especialidad',
    'usuarios.col_validity': 'Vigencia',
    'usuarios.col_status': 'Estado',
    'usuarios.col_actions': 'Acciones',
    'usuarios.active_btn': 'Activo',
    'usuarios.inactive_btn': 'Inactivo',
    'usuarios.out_of_date_msg': 'Fuera de vigencia',
    'usuarios.inactive_manual_msg': 'Inactivo manual',
    'usuarios.not_found': 'No se encontraron usuarios',
    'usuarios.adjust_filters': 'Ajusta los filtros o cambia el texto de búsqueda.',
    'usuarios.edit_user': 'Editar Usuario',
    'usuarios.create_new_user': 'Crear Nuevo Usuario',
    'usuarios.full_name': 'Nombre Completo *',
    'usuarios.full_name_placeholder': 'Ej: Juan Pérez García',
    'usuarios.email': 'Correo Electrónico *',
    'usuarios.email_placeholder': 'usuario@ejemplo.com',
    'usuarios.password': 'Contraseña',
    'usuarios.password_edit': '(dejar en blanco para no cambiar)',
    'usuarios.password_new': '*',
    'usuarios.password_placeholder': '••••••••',
    'usuarios.city_not_apply': 'No aplica',
    'usuarios.select_at_least_one_city': 'Selecciona al menos una ciudad.',
    'usuarios.select_at_least_one_specialty': 'Selecciona al menos una especialidad para el médico.',
    'usuarios.active_user': 'Usuario activo',
    'usuarios.validity_temp': 'Activación temporal (vigencia)',
    'usuarios.active_from': 'Activo desde *',
    'usuarios.active_until': 'Activo hasta *',
    'usuarios.auto_deactivate': 'Si llega la fecha "Activo hasta", el usuario se desactiva automáticamente, pero puedes reactivarlo manualmente cuando quieras.',
    'usuarios.role_permissions': 'Permisos del Rol',
    'usuarios.cancel': 'Cancelar',
    'usuarios.update_user': 'Actualizar Usuario',

    // Variables
    'var.title': 'Variables',
    'var.subtitle': 'Administra catálogos como especialidades y ciudades.',
    'var.tabs_specialties': 'Especialidades',
    'var.tabs_cities': 'Ciudades',
    'var.add_specialty': 'Agregar especialidad',
    'var.add_city': 'Agregar ciudad',
    'var.code': 'Código *',
    'var.code_placeholder_esp': 'ej: medicina_familiar',
    'var.code_placeholder_city': 'ej: puerto_penasco',
    'var.name': 'Nombre *',
    'var.name_placeholder_esp': 'ej: Medicina Familiar',
    'var.name_placeholder_city': 'ej: Puerto Peñasco',
    'var.create': 'Crear',
    'var.list': 'Listado',
    'var.col_name': 'Nombre',
    'var.col_code': 'Código',
    'var.col_status': 'Estado',
    'var.col_actions': 'Acciones',
    'var.active': 'Activa',
    'var.inactive': 'Inactiva',
    'var.no_records': 'No hay registros.',
    'var.deactivate_confirm': '¿Desactivar "{0}"?',

    // Auditoria
    'audit.title': 'Auditoría del Sistema',
    'audit.subtitle': 'Registro completo de todas las acciones realizadas',
    'audit.refreshing': 'Actualizando...',
    'audit.refresh': 'Actualizar',
    'audit.total': 'Total Registros',
    'audit.log': 'Registro de Actividades',
    'audit.no_records': 'No hay registros de auditoría',
    'audit.will_appear': 'Los registros aparecerán aquí cuando se realicen acciones',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.eventos': 'Events',
    'nav.pacientes': 'Patients',
    'nav.citas': 'Appointments',
    'nav.cirugias': 'Surgeries',
    'nav.triage': 'Pending Triages',
    'nav.consultas': 'Consultations',
    'nav.seguimientos': 'Follow-ups',
    'nav.usuarios': 'Users',
    'nav.variables': 'Variables',
    'nav.auditoria': 'Audit',
    'nav.logout': 'Logout',
    'panel.recepcion': 'Reception Panel',
    'panel.triage': 'Triage Panel',
    'panel.medico': 'Medical Panel',
    'panel.admin': 'Admin Panel',
    'notif.recent': 'Recent Activity',
    'notif.view_all': 'View all',
    'notif.no_activity': 'No recent activity',
    'notif.last_actions': 'Latest system actions',
    'lang.toggle': 'Switch to Spanish',
    'common.loading': 'Loading…',
    'medico.title': 'Medical Office',
    'medico.subtitle': 'Waiting patients and completed consultations',
    'medico.stats.waiting': 'Waiting',
    'medico.stats.completed': 'Completed Today',
    'medico.stats.total': 'Total Consultations',
    'medico.stats.surgeries': 'Initiated Surgeries',
    'medico.patients.waiting': 'Waiting Patients',
    'medico.action.start_consultation': 'Start Consultation',
    'medico.form.title': 'Medical Consultation',
    'medico.form.patient_data': 'Patient Data',
    'medico.form.phone': 'Phone',
    'medico.form.age': 'Age',
    'medico.form.sex': 'Sex',
    'medico.form.years': 'years',
    'medico.form.vitals': 'Vital Signs',
    'medico.form.vitals.temp': 'Temperature',
    'medico.form.vitals.bp': 'Blood Pressure',
    'medico.form.vitals.hr': 'Heart Rate',
    'medico.form.vitals.rr': 'Respiratory Rate',
    'medico.form.vitals.o2': 'O2 Saturation',
    'medico.form.vitals.glucose': 'Glucose',
    'medico.form.vitals.weight': 'Weight',
    'medico.form.vitals.height': 'Height',
    'medico.form.medical_info': 'Medical Information',
    'medico.form.allergies': 'Allergies',
    'medico.form.background': 'Background',
    'medico.form.reason_current': 'Reason for Consultation and Current Illness',
    'medico.form.reason': 'Reason for Consultation *',
    'medico.form.current_illness': 'Current Illness *',
    'medico.form.physical_exam_title': 'Physical Examination',
    'medico.form.physical_exam': 'Physical Examination Findings *',
    'medico.form.diagnosis_title': 'Diagnosis',
    'medico.form.diagnosis': 'Medical Diagnosis *',
    'medico.form.treatment_plan': 'Treatment Plan',
    'medico.form.treatment': 'Treatment *',
    'medico.form.medications': 'Prescribed Medications',
    'medico.form.add_medication': 'Add Medication',
    'medico.form.medication_name': 'Medication',
    'medico.form.medication_dose': 'Dose',
    'medico.form.medication_freq': 'Frequency',
    'medico.form.medication_duration': 'Duration',
    'medico.form.studies': 'Indicated Studies or Analysis',
    'medico.form.add_study': 'Add Study',
    'medico.form.study_type': 'Study Type',
    'medico.form.study_indications': 'Indications',
    'medico.form.recommendations': 'Recommendations',
    'medico.form.next_consultation': 'Next Consultation',
    'medico.form.requires_followup': 'Follow-up for a future event',
    'medico.form.followup_note': 'Follow-up note',
    'medico.form.followup_note_placeholder': 'Example: Schedule a check-up, review results, treatment follow-up…',
    'medico.form.followup_event': 'Event to schedule',
    'medico.form.followup_event_pending': 'Pending (no event)',
    'medico.form.followup_calendar': 'Calendar availability',
    'medico.form.followup_calendar_empty': 'This event has no schedules for the appointment specialty.',
    'medico.form.requires_surgery': 'Requires Surgery Process',
    'medico.form.cancel': 'Cancel',
    'medico.form.complete': 'Complete Consultation',
    'medico.form.back': 'Back',
    'medico.form.no_type': 'No appointment type',
    'medico.form.patient': 'Patient',
    'dash.admin.title': 'Good morning, Administrator!',
    'dash.admin.subtitle': 'System administration and management panel',
    'dash.admin.badge': 'Total control of the medical system',
    'dash.admin.active_users': 'Active Users',
    'dash.admin.total_patients': 'Total Patients',
    'dash.admin.audit_logs': 'Audit Logs',
    'dash.admin.roles_config': 'Configured Roles',
    'dash.admin.sys_users': 'System Users',
    'dash.admin.users': 'users',
    'dash.admin.reception': 'Reception',
    'dash.admin.triage': 'Triage',
    'dash.admin.doctor': 'Doctor',
    'dash.admin.admin': 'Administrator',
    'dash.admin.manage_users': 'Manage Users',
    'dash.admin.quick_actions': 'Quick Actions',
    'dash.admin.create_user': 'Create User',
    'dash.admin.variables': 'Variables',
    'dash.admin.view_audit': 'View Audit',
    'dash.admin.manage_patients': 'Manage Patients',
    'dash.admin.sys_status': 'System Status',
    'dash.admin.os': 'Operating System',
    'dash.admin.normal': 'Normal',
    'dash.admin.db': 'Database',
    'dash.admin.active': 'Active',
    'dash.admin.connectivity': 'Connectivity',
    'dash.admin.optimal': 'Optimal',
    'dash.admin.recent_activity': 'Recent Activity',
    'dash.admin.view_all': 'View All',
    'dash.admin.no_activity': 'No recent activity registered in the database.',
    'dash.recep.title': 'Good morning, Reception!',
    'dash.recep.subtitle': 'Welcome to the medical management system',
    'dash.recep.no_event': 'No active event',
    'dash.recep.total_appts_today': 'Total Appointments Today',
    'dash.recep.registered_patients': 'Registered Patients',
    'dash.recep.completed_appts': 'Completed Appointments',
    'dash.recep.active_events': 'Active Events',
    'dash.recep.appts_today': 'Appointments Today',
    'dash.recep.appts': 'appointments',
    'dash.recep.scheduled': 'Scheduled',
    'dash.recep.in_triage': 'In Triage',
    'dash.recep.in_consultation': 'In Consultation',
    'dash.recep.completed': 'Completed',
    'dash.recep.view_all_appts': 'View all appointments',
    'dash.recep.quick_actions': 'Quick Actions',
    'dash.recep.register_patient': 'Register Patient',
    'dash.recep.schedule_appt': 'Schedule Appointment',
    'dash.recep.view_events': 'View Events',
    'dash.recep.view_surgeries': 'View Surgeries',
    'dash.triage.title': 'Good morning, Nursing!',
    'dash.triage.subtitle': 'Vital signs and patient triage management',
    'dash.triage.patients_today': 'patients on today\'s list',
    'dash.triage.pending_triage': 'Pending Triage',
    'dash.triage.in_progress': 'In Progress',
    'dash.triage.completed': 'Completed',
    'dash.triage.patients_today_title': 'Patients Today',
    'dash.triage.patients': 'patients',
    'dash.triage.go_to_triage': 'Go to Triage module',
    'dash.triage.activity_today': 'Today\'s Activity',
    'dash.triage.total_patients': 'Total Patients',
    'dash.triage.triage_progress': 'Triage Progress',
    'dash.triage.avg_time': 'Average Time',
    'dash.triage.min': 'min',
    'dash.triage.per_patient': 'per patient',
    'dash.triage.pending': 'Pending',
    'dash.medico.title': 'Good morning, Doctor!',
    'dash.medico.subtitle': 'Consultation and medical follow-up panel',
    'dash.medico.badge': 'Comprehensive medical management system',
    'dash.medico.appts_today': 'Consultations Today',
    'dash.medico.followups': 'Follow-ups',
    'dash.medico.pending': 'pending',
    'dash.medico.active_surgeries': 'Active Surgeries',
    'dash.medico.my_patients': 'My Patients',
    'dash.medico.patients_today': 'Patients Today',
    'dash.medico.consultations': 'consultations',
    'dash.medico.go_to_consultations': 'Go to Consultations',
    'dash.medico.followups_title': 'Follow-ups',
    'dash.medico.pending_schedule': 'Pending Schedule',
    'dash.medico.scheduled_appts': 'Scheduled Appointments',
    'dash.medico.total': 'Total',
    'dash.medico.view_all': 'View All',
    'dash.medico.quick_actions': 'Quick Actions',
    'dash.medico.consult_patient': 'Consult Patient',
    'dash.medico.view_patients': 'View Patients',
    'dash.medico.manage_surgeries': 'Manage Surgeries',
    'consultas.title': 'Medical Consultations',
    'consultas.subtitle': 'Patients ready for consultation',
    'consultas.years': 'years',
    'consultas.no_observations': 'No observations',
    'consultas.in_consultation': 'In Consultation',
    'consultas.empty_title': 'No patients in consultation',
    'consultas.empty_desc': 'Patients will appear here after passing through triage',
    'cirugias.title': 'Surgery Management',
    'cirugias.subtitle': 'Surgical processes, socio-economic studies and follow-ups',
    'cirugias.start_process': 'Start Surgery Process',
    'cirugias.total': 'Total',
    'cirugias.pending': 'Pending',
    'cirugias.scheduled': 'Scheduled',
    'cirugias.completed': 'Completed',
    'cirugias.followups': 'Follow-ups',
    'cirugias.search_placeholder': 'Search by patient, diagnosis or doctor...',
    'cirugias.all_statuses': 'All statuses',
    'cirugias.status.pending_study': 'Pending Study',
    'cirugias.status.study_completed': 'Study Completed',
    'cirugias.status.scheduled': 'Scheduled',
    'cirugias.status.completed': 'Completed',
    'cirugias.status.cancelled': 'Cancelled',
    'cirugias.specialty': 'Specialty',
    'cirugias.unspecified': 'Unspecified',
    'cirugias.location': 'Location',
    'cirugias.unassigned': 'Unassigned',
    'cirugias.est_cost': 'Estimated Cost',
    'cirugias.view_details': 'View Details',
    'cirugias.do_study': 'Conduct Study',
    'cirugias.add_followup': 'Add Follow-up',
    'cirugias.empty_title': 'No surgeries registered',
    'cirugias.empty_desc': 'Start by initiating the first surgery process',
    'seg.title': 'Medical Follow-ups',
    'seg.subtitle': 'Management and control of patient follow-ups',
    'seg.new': 'New Follow-up',
    'seg.pending': 'Pending',
    'seg.scheduled': 'Scheduled',
    'seg.completed': 'Completed',
    'seg.search': 'Search by name, file or diagnosis...',
    'seg.all': 'All',
    'seg.status.pending': 'Pending Schedule',
    'seg.status.scheduled': 'Appointment Scheduled',
    'seg.status.completed': 'Completed',
    'seg.diagnosis': 'Diagnosis',
    'seg.glucose': 'Blood glucose',
    'seg.required_exams': 'Required exams',
    'seg.next_appt': 'Next appointment',
    'seg.pharmacy': 'Pharmacy Referral',
    'seg.view_details': 'View Details',
    'seg.edit': 'Edit',
    'seg.quick_followup': 'Quick follow-up...',
    'seg.requires_scheduling': 'Schedule in a future event',
    'seg.followup_note': 'Follow-up note',
    'seg.followup_note_placeholder': 'Example: Patient needs a check-up, review results, continue treatment…',
    'seg.followup_event': 'Event to schedule',
    'seg.followup_event_pending': 'Pending (no event)',
    'seg.in_15_days': 'In 15 days',
    'seg.in_1_month': 'In 1 month',
    'seg.in_3_months': 'In 3 months',
    'seg.in_6_months': 'In 6 months',
    'seg.manual_schedule': 'Manual schedule',
    'seg.empty_title': 'No follow-ups',
    'seg.empty_desc_filtered': 'No follow-ups found with the applied filters',
    'seg.empty_desc': 'Patient follow-ups will appear here',
    'seg.clear_filters': 'Clear filters',
    'triage.title': 'Triage Station',
    'triage.subtitle': 'Patients with appointments for today -',
    'triage.no_event': 'No active event',
    'triage.total_today': 'Total Patients Today',
    'triage.no_capture': 'No Capture',
    'triage.in_progress': 'In Progress',
    'triage.completed': 'Completed',
    'triage.search': 'Search patient in today\'s list...',
    'triage.available_patients': 'Available Patients',
    'triage.no_appt_type': 'No appointment type',
    'triage.scheduled_for': 'Scheduled for',
    'triage.assigned_time': 'Assigned time:',
    'triage.temp': 'Temperature',
    'triage.pressure': 'Pressure',
    'triage.empty_patients': 'No available patients',
    'triage.modal_title': 'Vital Signs - Triage',
    'triage.appt': 'Appointment:',
    'triage.vitals': 'Vital Signs',
    'triage.temp_input': 'Temperature (°C) *',
    'triage.normal': 'Normal:',
    'triage.pressure_input': 'Blood Pressure *',
    'triage.hr_input': 'Heart Rate (bpm) *',
    'triage.resp_input': 'Respiratory Rate (rpm) *',
    'triage.o2_input': 'Oxygen Saturation (%)',
    'triage.glucose_input': 'Glucose (mg/dL)',
    'triage.anthropometry': 'Anthropometry',
    'triage.weight_input': 'Weight (kg) *',
    'triage.height_input': 'Height (cm) *',
    'triage.imc_calc': 'Calculated BMI',
    'triage.underweight': 'Underweight',
    'triage.normal_weight': 'Normal',
    'triage.overweight': 'Overweight',
    'triage.obesity': 'Obesity',
    'triage.observations': 'Observations',
    'triage.obs_placeholder': 'Additional observations about the patient\'s condition...',
    'triage.out_of_range': 'Vital Signs Out of Range',
    'triage.cancel': 'Cancel',
    'triage.save_progress': 'Save in Progress',
    'triage.complete_send': 'Complete and Send to Consultation',
    'triage.close': 'Close',

    // Pacientes
    'pac.title_medico': 'My Patients',
    'pac.title_recepcion': 'Patient Management',
    'pac.subtitle_medico': 'Patients who have attended or are scheduled in the system',
    'pac.subtitle_recepcion': 'Register and manage patient records',
    'pac.new': 'New Patient',
    'pac.search': 'Search by name, record or phone...',
    'pac.all': 'all',
    'pac.scheduled': 'scheduled',
    'pac.attended': 'attended',
    'pac.citas': 'appointments',
    'pac.not_found': 'No patients found',
    'pac.try_another': 'Try another search term',
    'pac.start_registering': 'Start by registering your first patient',
    'pac.register_first': 'Register First Patient',
    'pac.register_new': 'Register New Patient',
    'pac.full_name': 'Full Name',
    'pac.dob': 'Date of Birth',
    'pac.sex': 'Sex',
    'pac.phone': 'Phone',
    'pac.city': 'City',
    'pac.nationality': 'Nationality',
    'pac.mexican': 'Mexican',
    'pac.american': 'American',
    'pac.passport': 'American Passport',
    'pac.curp': 'CURP',
    'pac.photo': 'Patient Photo (Optional)',
    'pac.select_image': 'Select Image',
    'pac.no_file': 'No file selected',
    'pac.note': 'Note:',
    'pac.auto_id': 'A unique record number will be automatically generated for this patient.',
    'pac.cancel': 'Cancel',
    'pac.saving': 'Saving...',
    'pac.register': 'Register Patient',
    'pac.age': 'Age',
    'pac.years': 'years',
    'pac.birth': 'Birth',
    'pac.registration': 'Registration',
    'pac.full_record': 'View Full Record',
    'pac.start_surgery': 'Start Surgery Process',

    // Citas
    'citas.not_active': 'This event is not active. Appointments cannot be scheduled.',
    'citas.day_of_only': 'On the day of the appointment, you can only cancel or register arrival.',
    'citas.slot_taken': 'That slot is already taken by another appointment.',
    'citas.title': 'Appointments',
    'citas.subtitle': 'General appointment manager: shows all appointments (all events and specialties) and allows scheduling in available slots.',
    'citas.no_events': 'No events available',
    'citas.create_event': 'Create an event with dates and times to enable available slots.',
    'citas.agenda': 'Agenda',
    'citas.followups_pending': 'Pending follow-ups',
    'citas.followups_selected': 'Selected follow-up',
    'citas.followups_clear': 'Clear',
    'citas.followups_pick_slot': 'Pick a time block in the calendar to schedule.',
    'citas.followups_empty': 'No pending follow-ups to schedule.',
    'citas.followups_action': 'Schedule',
    'citas.followups_msg_selected': 'Follow-up ready. Pick a time block in the calendar to schedule.',
    'citas.followups_wrong_event': 'This follow-up can only be scheduled in the selected event. Pick a slot within that event.',

    // Eventos
    'eventos.no_date': 'No date',
    'eventos.title': 'Event Agenda',
    'eventos.subtitle': 'View events as cards and enter their details to consult information, specialties, and agenda.',
    'eventos.new': 'New Event',
    'eventos.no_city_msg': 'Your user has no assigned city. Assign a city (or cities) to the user to view events.',
    'eventos.no_events_admin': 'No registered events',
    'eventos.no_events_city': 'No events for your city',
    'eventos.create_to_enable': 'Create an event to enable schedules and capacities.',
    'eventos.assigned_city': 'Assigned city:',
    'eventos.create': 'Create Event',
    'eventos.readonly': 'Read only',
    'eventos.inscriptions': 'Registrations',
    'eventos.event': 'Event',
    'eventos.no_specialties': 'No registered specialties',
    'eventos.specialties': 'specialties',
    'eventos.schedules': 'schedules',
    'eventos.view': 'View Event',
    'eventos.edit': 'Edit',
    'eventos.delete': 'Delete',
    'eventos.delete_title': 'Delete Event',
    'eventos.delete_desc': 'The event "{0}" will be deleted along with related specialties, schedules, practitioners, appointments, triage, and medical notes.',
    'eventos.cancel': 'Cancel',
    'eventos.delete_test': 'Delete (tests)',
    'eventos.delete_test_title': 'Delete Event (test mode)',
    'eventos.delete_test_desc': 'The event has ended and is normally read-only. Test mode allows force deletion.',

    // Usuarios
    'usuarios.title': 'User Management',
    'usuarios.subtitle': 'Manage system users',
    'usuarios.create': 'Create User',
    'usuarios.filters': 'Filters',
    'usuarios.search_label': 'Search',
    'usuarios.search_placeholder': 'Name, email, role, city or specialty...',
    'usuarios.role_label': 'Role',
    'usuarios.role_all': 'All',
    'usuarios.role_admin': 'Administrator',
    'usuarios.role_reception': 'Reception',
    'usuarios.role_triage': 'Triage',
    'usuarios.role_doctor': 'Doctor',
    'usuarios.city_label': 'City',
    'usuarios.city_all': 'All',
    'usuarios.status_label': 'Status',
    'usuarios.status_all': 'All',
    'usuarios.status_active': 'Active',
    'usuarios.status_inactive': 'Inactive (all)',
    'usuarios.status_inactive_manual': 'Manual inactive',
    'usuarios.status_out_of_date': 'Out of date',
    'usuarios.order_label': 'Order',
    'usuarios.order_name_asc': 'Name (A-Z)',
    'usuarios.order_name_desc': 'Name (Z-A)',
    'usuarios.order_role': 'Role',
    'usuarios.order_city': 'City',
    'usuarios.clear': 'Clear',
    'usuarios.users_title': 'Users',
    'usuarios.showing': 'Showing:',
    'usuarios.active': 'Active:',
    'usuarios.inactive': 'Inactive:',
    'usuarios.col_user': 'User',
    'usuarios.col_email': 'Email',
    'usuarios.col_role': 'Role',
    'usuarios.col_city': 'City',
    'usuarios.col_cities': 'Cities',
    'usuarios.col_specialty': 'Specialty',
    'usuarios.col_validity': 'Validity',
    'usuarios.col_status': 'Status',
    'usuarios.col_actions': 'Actions',
    'usuarios.active_btn': 'Active',
    'usuarios.inactive_btn': 'Inactive',
    'usuarios.out_of_date_msg': 'Out of date',
    'usuarios.inactive_manual_msg': 'Manual inactive',
    'usuarios.not_found': 'No users found',
    'usuarios.adjust_filters': 'Adjust filters or change the search text.',
    'usuarios.edit_user': 'Edit User',
    'usuarios.create_new_user': 'Create New User',
    'usuarios.full_name': 'Full Name *',
    'usuarios.full_name_placeholder': 'Ex: John Doe',
    'usuarios.email': 'Email *',
    'usuarios.email_placeholder': 'user@example.com',
    'usuarios.password': 'Password',
    'usuarios.password_edit': '(leave blank to keep)',
    'usuarios.password_new': '*',
    'usuarios.password_placeholder': '••••••••',
    'usuarios.city_not_apply': 'Not applicable',
    'usuarios.select_at_least_one_city': 'Select at least one city.',
    'usuarios.select_at_least_one_specialty': 'Select at least one specialty for the doctor.',
    'usuarios.active_user': 'Active user',
    'usuarios.validity_temp': 'Temporary activation (validity)',
    'usuarios.active_from': 'Active from *',
    'usuarios.active_until': 'Active until *',
    'usuarios.auto_deactivate': 'If the "Active until" date is reached, the user is automatically deactivated, but you can manually reactivate them anytime.',
    'usuarios.role_permissions': 'Role Permissions',
    'usuarios.cancel': 'Cancel',
    'usuarios.update_user': 'Update User',

    // Variables
    'var.title': 'Variables',
    'var.subtitle': 'Manage catalogs such as specialties and cities.',
    'var.tabs_specialties': 'Specialties',
    'var.tabs_cities': 'Cities',
    'var.add_specialty': 'Add specialty',
    'var.add_city': 'Add city',
    'var.code': 'Code *',
    'var.code_placeholder_esp': 'e.g.: family_medicine',
    'var.code_placeholder_city': 'e.g.: puerto_penasco',
    'var.name': 'Name *',
    'var.name_placeholder_esp': 'e.g.: Family Medicine',
    'var.name_placeholder_city': 'e.g.: Puerto Peñasco',
    'var.create': 'Create',
    'var.list': 'List',
    'var.col_name': 'Name',
    'var.col_code': 'Code',
    'var.col_status': 'Status',
    'var.col_actions': 'Actions',
    'var.active': 'Active',
    'var.inactive': 'Inactive',
    'var.no_records': 'No records.',
    'var.deactivate_confirm': 'Deactivate "{0}"?',

    // Auditoria
    'audit.title': 'System Audit',
    'audit.subtitle': 'Complete record of all actions performed',
    'audit.refreshing': 'Refreshing...',
    'audit.refresh': 'Refresh',
    'audit.total': 'Total Records',
    'audit.log': 'Activity Log',
    'audit.no_records': 'No audit records',
    'audit.will_appear': 'Records will appear here when actions are performed',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'es';
  });

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const next = prev === 'es' ? 'en' : 'es';
      localStorage.setItem('app_language', next);
      return next;
    });
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
